### ISSUE TITLE
Opentelemetry api dependency missing

### ISSUE THREAD

**Issue by Tomas-Eminger** [terra-money/oracle-feeder#46]
When trying to start:

> @terra-money/price-server@1.4.5 start /home/terra/oracle-feeder/price-server
> node --stack_size=4096 --max-old-space-size=4096 -r ts-node/register/transpile-only -r tsconfig-paths/register src/main.ts

Error: Cannot find module '@opentelemetry/api'
Require stack:
- /home/terra/oracle-feeder/price-server/node_modules/@opentelemetry/exporter-prometheus/build/src/PrometheusExporter.js
- /home/terra/oracle-feeder/price-server/node_modules/@opentelemetry/exporter-prometheus/build/src/index.js
- /home/terra/oracle-feeder/price-server/src/lib/metrics.ts
- /home/terra/oracle-feeder/price-server/src/provider/base/Quoter.ts
- /home/terra/oracle-feeder/price-server/src/provider/base/index.ts
- /home/terra/oracle-feeder/price-server/src/provider/fiat/FiatProvider.ts
- /home/terra/oracle-feeder/price-server/src/provider/index.ts
- /home/terra/oracle-feeder/price-server/src/main.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._resolveFilename (/home/terra/oracle-feeder/price-server/node_modules/tsconfig-paths/lib/register.js:75:40)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/terra/oracle-feeder/price-server/node_modules/@opentelemetry/exporter-prometheus/src/PrometheusExporter.ts:17:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/terra/oracle-feeder/price-server/node_modules/@opentelemetry/exporter-prometheus/src/index.ts:17:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @terra-money/price-server@1.4.5 start: `node --stack_size=4096 --max-old-space-size=4096 -r ts-node/register/transpile-only -r tsconfig-paths/register src/main.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @terra-money/price-server@1.4.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

Add module helped:

`npm install @opentelemetry/api`

**Comment by hanjukim** [comment]
Could you make a PR?
