### ISSUE TITLE
Error: Non 5-bit word

### ISSUE THREAD

**Issue by athenawisdoms** [terra-money/oracle-feeder#71]
After running `npm start update-key` and entering the 24-word bip39 mnemonic of the feeder account when prompted, I get the error

```
Error: Non 5-bit word
    at Object.encode (/home/aw/oracle-feeder/feeder/node_modules/bech32/dist/index.js:95:23)
    at MnemonicKey.get (/home/aw/oracle-feeder/feeder/node_modules/@terra-money/terra.js/src/key/Key.ts:50:19)
    at Object.save (/home/aw/oracle-feeder/feeder/src/keystore.ts:76:36)
    at updateKey (/home/aw/oracle-feeder/feeder/src/updateKey.ts:34:18)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async main (/home/aw/oracle-feeder/feeder/src/index.ts:112:5)
```

I'm using commit https://github.com/terra-money/oracle-feeder/commit/dba87f762726a1a0c2d69076c08659e26c4677a8, node `v14.19.3` and Ubuntu 20.04. Problem goes away on release `v2.0.1`

How can I fix this problem on my system? Thanks!

**Comment by emidev98** [comment]
Hello @athenawisdoms, I assume the issue is not relevant anymore or you have upgraded the version of the oracle feeder. If the issue is not solved please open it again or if there is any other new issue I encourage you to open it again. Thanks!
